Sprint2
oier-elorrieta/R3-JOEL-MIKEL-UNAI-DDBB pull request #2
Opened 2021-02-08 10:06 UTC by joelfano

Sprint2 hecho, esperamos la respuesta cuanto antes.
Un saludo, Joel, Mikel y Unai

2021-02-09 20:54 UTC, Jose-Elorrieta requested changes
Está bastante bien. Solo hay que hacer unos pocos cambios:
En el diagrama E-R:
- En la entidad Producto nos hace falta no solo el precio de venta, sino también el de compra.
En el paso a tablas:
- La relación Contiene no es necesaria si ponemos en Producto los dos precios (de compra y de venta). La información que proporciona esta relación nos la da la relación tiene del supertipo Operaciones. Si la operación es un aprovisionamiento, el atributo Precio_actual será un precio de compra y en cualquier otro caso (ticket, factura, pedido o comanda) será un precio de venta.
En el script de creación de la BD (diseño físico):
- La relación provee entre Aprovisionamiento y Fabricante no es N:M, por lo que no debe dar lugar a una nueva tabla.
- En la tabla Tiene sobre el atributo Total_producto, que no aparece en el diagrama E-R ni el esquema relacional.
- La clave ajena Num_Trans en la tabla Incluye no es correcta, ¿a qué tabla debe apuntar?

¡Vais muy bien! Corregid estos errores y me lo volvéis a enviar.

2021-02-10 18:26 UTC, Jose-Elorrieta commented
También tenéis que meter datos en la tabla Vende que indica qué productos vende cada local. 
Al entrar un usuario en la aplicación, este usuario estará asociado a un local y solo deberá poder seleccionar productos que estén a la venta en su local, no en otros. 
Por otro lado, los precios son numéricos. Aunque MySQL permite ponerlos entre comillas (es demasiado permisivo, para mi gusto) no se deben poner entre comillas los datos numéricos.

2021-02-10 21:04 UTC, Jose-Elorrieta approved these changes
De acuerdo. Os doy mi visto bueno. Modificad una cosa, y es que en la tabla Vende los NIF deben ir entre comillas porque son cadenas de caracteres. 
¡ENHORABUENA! Sois los primeros para los que doy el visto bueno al sprint 2.

2021-02-12 08:34 UTC, Jose-Elorrieta approved these changes

2021-02-12 08:44 UTC, oier-elorrieta approved these changes

2021-02-12 08:45 UTC, oier-elorrieta commented
Visto bueno de Jose dado

2021-02-12 09:11 UTC, merged